import {StyleSheet, Dimensions} from 'react-native';
import {RFValue} from 'react-native-responsive-fontsize';
import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from 'react-native-responsive-screen';

const height = Dimensions.get('screen').height;

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8f9fd',
  },
  statusContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    width: wp('18%'),
    backgroundColor: '#ccd3dd',
    borderRadius: 20,
    margin: '5%',
  },
  statusText: {
    color: 'white',
    fontSize: RFValue(15, height),
    textTransform: 'capitalize',
    paddingVertical: hp('.5%'),
  },
  mianContainer: {
    flexDirection: 'row',
    width: wp('90%'),
    height: hp('15%'),
    backgroundColor: 'white',
    alignSelf: 'center',
    borderRadius: 20,
    elevation: 3,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: '2%',
    shadowColor: 'black',
    shadowOffset: {height: 2, width: 0},
    shadowOpacity: 0.26,
    shadowRadius: 3,
  },
  invoiceText: {
    paddingBottom: hp('1%'),
    color: 'grey',
    fontSize: RFValue(12, height),
  },
  nameText: {
    color: 'grey',
    fontWeight: 'bold',
    fontSize: RFValue(18, height),
  },
  phoneNumberText: {
    color: 'grey',
    fontSize: RFValue(12, height),
  },
  contactText: {
    color: 'grey',
    fontWeight: 'bold',
    fontSize: RFValue(14, height),
  },
  textContainer: {
    paddingVertical: '2%',
    margin: '5%',
  },
  totalAmountContainer: {
    backgroundColor: '#f2f2f2',
    height: '85%',
    width: '35%',
    borderRadius: 20,
    justifyContent: 'center',
  },
  totalAmountText: {
    fontSize: RFValue(12, height),
    color: 'grey',
    fontWeight: 'bold',
    alignSelf: 'center',
  },
  amountText: {
    fontSize: RFValue(22, height),
    color: 'black',
    fontWeight: 'bold',
    alignSelf: 'center',
    paddingVertical: '5%',
  },
  dateText: {
    fontSize: RFValue(12, height),
    color: 'grey',
    alignSelf: 'center',
    fontWeight: 'bold',
    marginLeft: wp('2%'),
  },
  dateContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  dot: {
    height: 7,
    width: 7,
    borderRadius: 10,
    borderWidth: 1,
    backgroundColor: 'red',
    borderColor: 'red',
  },
  middleContainer: {
    flexDirection: 'row',
    paddingTop: hp('5%'),
    justifyContent: 'space-between',
    paddingHorizontal: wp('5%'),
  },
  notesContainer: {
    flexDirection: 'row',
    paddingTop: hp('2%'),
    justifyContent: 'space-between',
    paddingHorizontal: wp('5%'),
  },
  hairRemovalContainer: {
    flexDirection: 'row',
    paddingTop: hp('1%'),
    justifyContent: 'space-between',
    paddingHorizontal: wp('5%'),
  },
  serviceNameContainer: {width: '60%'},
  serviceText: {
    color: '#979ea3',
    fontWeight: 'bold',
  },
  totalPriceText: {
    color: '#979ea3',
    fontWeight: 'bold',
    paddingRight: '5%',
  },
  noteText: {
    color: '#979ea3',
    fontWeight: 'bold',
    width: '60%',
  },
  serviceNameText: {
    color: 'black',
    fontWeight: 'bold',
    // marginLeft: '10%',
  },
  totalText: {
    color: 'black',
    fontWeight: 'bold',
  },
  listContainer: {
    width: '90%',
    marginTop: '2%',
    borderRadius: 10,
    alignSelf: 'center',
    backgroundColor: 'white',
    paddingHorizontal: '4%',
    paddingVertical: '1%',
  },
  list: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: hp('1%'),
  },
  mainSubContainer: {flexDirection: 'row', alignItems: 'center'},
  seperator: {
    height: 1,
    width: '90%',
    alignSelf: 'center',
    backgroundColor: 'lightgrey',
    marginTop: '3%',
  },
  button: {
    backgroundColor: '#47b8d6',
    width: '40%',
    alignSelf: 'center',
    alignItems: 'center',
    paddingVertical: '3%',
    marginBottom: '5%',
    borderRadius: 10,
    position: 'absolute',
    bottom: 0,
    justifyContent: 'center',
  },
  greyButton: {
    backgroundColor: 'grey',
    width: '40%',
    alignSelf: 'center',
    alignItems: 'center',
    paddingVertical: '3%',
    marginBottom: '5%',
    borderRadius: 10,
    position: 'absolute',
    bottom: 0,
    justifyContent: 'center',
  },
  buttonText: {color: 'white', fontWeight: 'bold'},
});
